export const projects = [
  {
    id: 'news-today',
    slug: 'news-today',
    title: 'NEWS TODAY',
    sub: 'Full Stack News Platform',
    desc: 'A full-stack news experience with a React frontend, NestJS API, MongoDB persistence, and Axios-powered communication. It is built for speed, clarity, and a clean reading signal.',
    tags: ['React', 'Tailwind', 'Axios', 'NestJS', 'MongoDB'],
    color: '#D4AF77',
    year: '2025',
    featured: true,
    emoji: '📰',
    href: '/projects/news-today',
    link: 'https://newstoday-client.vercel.app/',
    source: 'https://github.com/mahmoudmoataz99/news2day',
  },
  {
    id: 'eventbook',
    slug: 'eventbook',
    title: 'EVENTBOOK',
    sub: 'Event Management Platform',
    desc: 'Full-stack event booking platform featuring React, Swiper carousels, a Node/Express backend, and MongoDB. Designed so discovering and booking events feels effortless.',
    tags: ['React', 'Tailwind', 'Swiper', 'NodeJS', 'MongoDB', 'Express'],
    color: '#D4AF77',
    year: '2025',
    featured: true,
    emoji: '📅',
    href: '/projects/eventbook',
    link: 'https://events-booker.vercel.app/',
    source: 'https://github.com/mahmoudmoataz99/Events-Booker',
  },
  {
    id: 'adidas-clone',
    slug: 'adidas-clone',
    title: 'ADIDAS CLONE',
    sub: 'E-Commerce UI Clone',
    desc: 'Pixel-precise Adidas storefront clone built with Angular and Bootstrap that has responsive product pages that capture the energy of a real retail experience.',
    tags: ['Angular', 'Bootstrap'],
    color: '#D4AF77',
    year: '2024',
    featured: false,
    emoji: '👟',
    href: '/projects/adidas-clone',
    link: 'https://adidas-angular.vercel.app/',
    source: 'https://github.com/mahmoudmoataz99/adidas-angular',
  },
  {
    id: 'jubari-clone',
    slug: 'jubari-clone',
    title: 'JUBARI CLONE',
    sub: 'Travel Agency Experience',
    desc: 'Responsive travel agency clone with Angular, Bootstrap, and a Laravel/MySQL backend where journeys presented with clarity and polish.',
    tags: ['Angular', 'Bootstrap', 'Laravel', 'MySQL'],
    color: '#D4AF77',
    year: '2024',
    featured: false,
    emoji: '✈️',
    href: '/projects/jubari-clone',
    link: 'https://jubari-clone-4z7cvqvsm-mahmoud-moatazs-projects.vercel.app/',
    source: 'https://github.com/mahmoudmoataz99/jubari-clone',
  },
  {
    id: 'finexo',
    slug: 'finexo',
    title: 'FINEXO',
    sub: 'Finance Landing Page',
    desc: 'Modern finance-themed landing page with interactive JavaScript components and a Bootstrap layout made with confidence and clarity in every section.',
    tags: ['HTML', 'CSS', 'Bootstrap', 'JavaScript'],
    color: '#D4AF77',
    year: '2023',
    featured: false,
    emoji: '💹',
    href: '/projects/finexo',
    link: 'https://mahmoudmoataz99.github.io/Finexo/',
    source: 'https://github.com/mahmoudmoataz99/Finexo',
  },
  {
    id: 'wiki-search',
    slug: 'wiki-search',
    title: 'WIKI SEARCH',
    sub: 'Wikipedia Search Tool',
    desc: 'Browser-based Wikipedia search powered by the MediaWiki API.',
    tags: ['HTML', 'CSS', 'Bootstrap', 'JavaScript'],
    color: '#D4AF77',
    year: '2023',
    featured: false,
    emoji: '🔍',
    href: '/projects/wiki-search',
    link: 'https://mahmoudmoataz99.github.io/Wiki-Search/',
    source: 'https://github.com/mahmoudmoataz99/Wiki-Search',
  },
  {
    id: 'little-fashion',
    slug: 'little-fashion',
    title: 'LITTLE FASHION',
    sub: 'Fashion Landing Page',
    desc: 'Elegant fashion brand landing page with clean HTML/CSS and responsive layout.',
    tags: ['HTML', 'CSS'],
    color: '#D4AF77',
    year: '2022',
    featured: false,
    emoji: '👗',
    href: '/projects/little-fashion',
    link: 'https://mahmoudmoataz99.github.io/little-fashion/index.html',
    source: 'https://github.com/mahmoudmoataz99/little-fashion',
  },
]

export const skills = [
  { name: 'React', level: 88, category: 'Frontend' },
  { name: 'Angular', level: 80, category: 'Frontend' },
  { name: 'Next.js', level: 70, category: 'Frontend' },
  { name: 'TypeScript', level: 90, category: 'Frontend' },
  { name: 'JavaScript', level: 90, category: 'Frontend' },
  { name: 'HTML', level: 95, category: 'Frontend' },
  { name: 'CSS', level: 90, category: 'Frontend' },
  { name: 'Tailwind', level: 88, category: 'Frontend' },
  { name: 'Bootstrap', level: 85, category: 'Frontend' },
  { name: 'PHP', level: 80, category: 'Backend' },
  { name: 'Laravel', level: 75, category: 'Backend' },
  { name: 'Node.js', level: 78, category: 'Backend' },
  { name: 'NestJS', level: 75, category: 'Backend' },
  { name: 'MongoDB', level: 76, category: 'Database' },
  { name: 'MySQL', level: 72, category: 'Database' },
]

export const experience = [
  {
    date: '07/2025 – 03/2026',
    role: 'Frontend Developer',
    co: 'Info-Tech Global',
    desc: 'Developing and maintaining web applications with React and NestJS. Focused on performance optimization and seamless API integration.',
  },
  {
    date: '01/2025 – 03/2025',
    role: 'React Intern',
    co: 'ABS.AI',
    desc: 'Built dynamic web applications using React, collaborating with design teams to create responsive interfaces.',
  },
  {
    date: '09/2024 – 12/2024',
    role: 'Frontend Intern',
    co: 'Yearex Group',
    desc: 'Redesigned company website using Angular, implementing responsive UI components.',
  },
  {
    date: '06/2019 – 07/2019',
    role: 'Summer IT Trainee',
    co: 'QNB AL-AHLI',
    desc: 'Explored the IT department end-to-end & discovered the ways for problem-solving culture, modern tooling, and how systems stay reliable under pressure.',
  },
]

export const education = [
  {
    date: '11/2023 – 07/2024',
    certificate: 'Full Stack Diploma',
    co: 'YAT Learning Center',
  },
  {
    date: '2018 – 2023',
    certificate: 'B.Sc. Computer Engineering',
    co: 'MSA University / Greenwich University',
  },
  {
    date: '2015 – 2018',
    certificate: 'IGCSE',
    co: 'Orouba Language Schools',
  },
]
